parameters:
#    cornichon_user.example.class: Cornichon\UserBundle\Example

services:
#    cornichon_user.example:
#        class: %cornichon_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
